services:

  webapp:
    image: harry530/crud:1.4
    ports:
      - 8080:80
    
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Harrii  
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql/
  
  dbui:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

volumes:
    data:

    